# Generated by Django 5.2.4 on 2025-07-19 03:58

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FotoGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to=App.models.ruta_imagen_galeria, verbose_name='Imagen')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('destacada', models.BooleanField(default=False, verbose_name='Destacar foto')),
            ],
            options={
                'verbose_name': 'Foto de Galería',
                'verbose_name_plural': 'Fotos de Galería',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
