# Generated by Django 5.2.4 on 2025-07-19 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotogaleria',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='fotogaleria',
            name='destacada',
        ),
        migrations.RemoveField(
            model_name='fotogaleria',
            name='titulo',
        ),
    ]
